### ISSUE TITLE
change and document new proxy url

### ISSUE THREAD

**Issue by jchartrand** [cwrc/getty-entity-lookup#1]
https://lookup.services.cwrc.ca/getty

**Comment by jchartrand** [comment]
I've made the change, and tested locally, and have generated a new NPM release.  Once Andrew and I finish sorting out the dev server, then I'll update the dbpedia-entity-lookup and getty-entity-lookup packages in CWRC-GitWriterDev, and finally upload it all to dev-cwrc-writer.cwrc.ca

**Comment by ilovan** [comment]
isn't this part of https://github.com/cwrc/CWRC-WriterBase/issues/33? If so, I'll move to DeployToProd

**Comment by jchartrand** [comment]
Yes, it was to track that there were changes needed in the individual repositories.
